language: python
python:
  - 3.5
  - 3.6

env:
    global:
        - UNICODE_WIDTH=32
        - PLAT=x86_64
        - MB_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
        - VERSION=$(echo $TRAVIS_TAG | sed s/v//)
os:
  - linux

dist: xenial

services: docker
sudo: required

matrix:
    fast_finish: true
    include:
        - python: 3.7
          sudo: true
        - python: 3.8
          sudo: true
          env: MB_ML_VER=2010
        - python: 3.9
          sudo: true
          env: MB_ML_VER=2010
        - python: 3.9
          dist: xenial
          sudo: true
          env: MB_ML_VER=2010
        - compiler: clang
          python: 3.7
          env:
            - SCAN="scan-build --status-bugs"
            - SOURCEDEPLOY=1
            - MKDOC="-DBUILD_DOC=ON -DSPHINX_ARGS=-WT"
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.5
          python: 3.5
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.6
          python: 3.6
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.7
          python: 3.7
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.8
          python: 3.8
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.9
          python: 3.9

addons:
    apt:
      sources:
        - sourceline: 'ppa:jokva/backports'
        - george-edison55-precise-backports # cmake 3
      packages:
        - cppcheck
        - cmake
        - cmake-data

before_install:
    - git clone https://github.com/matthew-brett/multibuild
    - unset -f pushd
    - unset -f popd
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
  - pip install -r requirements.txt
  - pip install -r requirements-doc.txt
  - pip install setuptools setuptools-scm scikit-build
  - pip install bandit pytest pytest-runner

before_script:
  - enabled="-DBUILD_PYTHON=OFF -DBUILD_MEX=OFF"
  - if [[ -n "${MB_PYTHON_VERSION+1}" ]]; then
        enabled="$enabled -DBUILD_PYTHON=ON -DREQUIRE_PYTHON=ON";
    fi
  - bandit -c bandit.yml -r python
  - cmake --version
  - mkdir build
  - pushd build
  - $SCAN cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DBUILD_SHARED_LIBS=ON
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_NAME_DIR=/usr/local/lib
          $MKDOC
          $enabled ..
  - if command -v cppcheck; then
        cppcheck
             --enable=style,portability,performance,warning
             --library=posix
             --library=$TRAVIS_BUILD_DIR/cppcheck/segyio.cfg
             --suppressions-list=$TRAVIS_BUILD_DIR/cppcheck/suppressions.txt
             --inline-suppr
             --project=compile_commands.json
             --error-exitcode=1
        ;
    fi
  - popd

# distutils/setuptools on macos ignores the --rpath argument, so set
# DYLD_LIBRARY_PATH so that the freshly-built image is picked up on for the
# tests.
#
# segyio is configured with CMAKE_INSTALL_NAME_DIR so that the wheel build on
# OS X so the delocate tool can figure out what dylib to include.
script:
  - pushd build
  - export DYLD_LIBRARY_PATH=$PWD/lib
  - $SCAN make && ctest --output-on-failure
  - sudo make install
  - popd
  # install works, so remove the _skbuild because it having root permissions
  # from make install breaks build_wheel
  - sudo rm -rf python/_skbuild
  - build_wheel python $PLAT
  - install_run $PLAT
  - mv wheelhouse python/dist

before_deploy:
  # OS X ships with a tar that doesn't support --exclude-vcs, which is
  # unproblematic as long as source code is uploaded from linux.
  #
  # when doing source deploy, remove the dist directory with pre-built wheels,
  # otherwise they get picked up instead, which will surely fail because the
  # wheel has already been uploaded to pypi.
  - if [[ "$TRAVIS_OS_NAME" == "linux" && ! -d segyio-$VERSION ]]; then
      git clone $TRAVIS_BUILD_DIR segyio-$VERSION;
      echo "version = '$TRAVIS_TAG'" > segyio-$VERSION/python/segyio/version.py;
      tar --exclude-vcs -C $TRAVIS_BUILD_DIR -czvf segyio-$VERSION.tar.gz segyio-$VERSION;
      zip --exclude *.git -r segyio-$VERSION.zip $TRAVIS_BUILD_DIR/segyio-$VERSION/*;
    fi
  - pushd python
  - if [[ $SOURCEDEPLOY ]]; then
      rm -rf dist;
    fi

after_deploy:
  - popd

deploy:
    - provider: pypi # upload built wheels and source tarball
      skip_cleanup: true
      skip_upload_docs: true
      skip_existing: true
      user: statoil-travis
      distributions: --skip-cmake build sdist
      password:
        secure: BaPED+fUXxmk61N/RtrEWtlRKinc2d+VodwKxwlq/74n8Z6RfJKp/ZzlinbjtnpLB/1kPphxwCYLuG2N2nU2kttNJCQEw9AlPL1gnDxDVUz83KuxSsqLPj9VOdj9MI3xyUs+LC3PW2N4kw2dB+/n2pB7BIwvA+Ykx6+Z2eD2vyEV8WqndP6+vApracCbE8huNfsnbxMqr188qzXbTRnzR1pwVFYBTNJ5vfRf0z/NmHXFpRhKEUaaqazJaax1xp5FGVFg2Wy4GQVDvtn6bVpu/rV5wyWXXdXSqqAQmrwv10OZt5ROfb88yfx+ZilpYDeiHmH8YLj4BjcLpdNeNW0c/irgtejLpnd7+XTUKl2QJzDr2l2ShhuaT+ZN7W8iXXZ4xPPvgcudF9fELZXMy6sKXLPE9qhL1yo/1x2eQ662PgusyegoBcQxtJvc0I0ct7jpWUMU0YQhu6VQUDTaxluSw7kxmQ2WYIW0UJIMkn+AkPw8t/ZYa83RbteRM3I7bAthzNl0IF/t5rDUt8itb6f4eTxjP1+5QdlNkSTNG9KXIxP8wX843PtFKA1i8gcqCIppgoQAnEHHcTJ+nX/ilqXHBWIDiYX6k79B3Hflqj1IcBZjwbUdojLRsHuNb8JN0y8aNsrWyYKhV09+AmvFwo3pY543HOHq/Fuux9ZCUCTeLbo=
      on:
        tags: true

    - provider: releases # upload tarball and zip with source code
      skip_cleanup: true
      overwrite: true
      file:
        - $TRAVIS_BUILD_DIR/segyio-$VERSION.tar.gz
        - $TRAVIS_BUILD_DIR/segyio-$VERSION.zip
      api_key:
        secure: VdV/5kCCwUFwgU7wvKRrOy4u9nnvLsM3RoW1G2z8w8e838fcTeXLU3Zu8rLzLpcaXJKX07WNQmG85PZrgRjB9mzZAbXnPJeMk5MT3YVWaiyF6zNxK+mQQOvTCJ8P25nm5Iq1PLtIW/wM1RqNLgT8t3AsLiIva+6JK+2wGA2ilOl2YVgJqEiZV1f9DJutPewDf8pqYrnrHktMmkio/uubc12MLFOrNeQxK/EJahw7x56q8EcxrJXHnv6T2zEvUdcEYfRvIrT62jiVqiJP9wmUVdq2x8/RlgRzcCpGhy2o17iMUIH228so2hbu5/NcvtAh/LUDeqlhQ1YLRp1vO6H8Uh9B6aJgBNPwYmrKBHQQD27l5vt74DNJuqsXTZtrQlzUiiptKTV7mjFckF7mG04d1J/0GcVcxjpRZa3rp85KymQKWTsuWJYrCWSeVh+SMwUAbMZ3/vhEKPtrf4rwI+4INTitLuBNfcyH0W+W/rWLBMYoojRW0NJjc+4HJGpkMPbFkDjpde31ZqgI/Cec0GPpqbtsb3DkK/f4mLrR+F59b3+Lj0Cjyh9lM2fVXTrPYt13kdwbtBnNy6x2kdTkEBCk9m+eTFAfJGal+3SwgLeiGQdkjdZ7vSLwwdRf7Qvz5WjxKQ+feFWm+qi0GurWOEaZrubB82CGukxOXKzrvAGN3Eo=
      on:
        tags: true
        condition: $SOURCEDEPLOY
